version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: actual_web_1
      APP_PORT: 5006
      PROXY_AUTH_ADD: "false"

  web:
    user: 1000:1000
    image: ghcr.io/actualbudget/actual:sha-4dba958@sha256:a22cafc52d51d7f84b1f1d30a3fbd6ad53b792edc04f627067216e9f0517d714
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
